const languages = [
  { code: "en-US", name: "American", flag: "https://flagcdn.com/w320/us.png" },
  { code: "ko-KR", name: "Korean", flag: "https://flagcdn.com/w320/kr.png" },
  { code: "ar-SA", name: "Arabic", flag: "https://flagcdn.com/w320/sa.png" },
  {
    code: "pt-BR",
    name: "Portuguese (Brazil)",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    code: "pt-PT",
    name: "Portuguese (Portugal)",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  { code: "ru-RU", name: "Russian", flag: "https://flagcdn.com/w320/ru.png" },
  { code: "it-IT", name: "Italian", flag: "https://flagcdn.com/w320/it.png" },
  { code: "nl-NL", name: "Dutch", flag: "https://flagcdn.com/w320/nl.png" },
  { code: "sv-SE", name: "Swedish", flag: "https://flagcdn.com/w320/se.png" },
  { code: "no-NO", name: "Norwegian", flag: "https://flagcdn.com/w320/no.png" },
  { code: "da-DK", name: "Danish", flag: "https://flagcdn.com/w320/dk.png" },
  { code: "fi-FI", name: "Finnish", flag: "https://flagcdn.com/w320/fi.png" },
  { code: "pl-PL", name: "Polish", flag: "https://flagcdn.com/w320/pl.png" },
  { code: "tr-TR", name: "Turkish", flag: "https://flagcdn.com/w320/tr.png" },
  { code: "he-IL", name: "Hebrew", flag: "https://flagcdn.com/w320/il.png" },
  { code: "hu-HU", name: "Hungarian", flag: "https://flagcdn.com/w320/hu.png" },
  { code: "cs-CZ", name: "Czech", flag: "https://flagcdn.com/w320/cz.png" },
  { code: "sk-SK", name: "Slovak", flag: "https://flagcdn.com/w320/sk.png" },
  { code: "ro-RO", name: "Romanian", flag: "https://flagcdn.com/w320/ro.png" },
  { code: "bg-BG", name: "Bulgarian", flag: "https://flagcdn.com/w320/bg.png" },
  { code: "uk-UA", name: "Ukrainian", flag: "https://flagcdn.com/w320/ua.png" },
  {
    code: "vi-VN",
    name: "Vietnamese",
    flag: "https://flagcdn.com/w320/vn.png",
  },
  { code: "th-TH", name: "Thai", flag: "https://flagcdn.com/w320/th.png" },
  { code: "ms-MY", name: "Malay", flag: "https://flagcdn.com/w320/my.png" },
  {
    code: "id-ID",
    name: "Indonesian",
    flag: "https://flagcdn.com/w320/id.png",
  },
  { code: "tl-PH", name: "Tagalog", flag: "https://flagcdn.com/w320/ph.png" },
  { code: "bn-BD", name: "Bengali", flag: "https://flagcdn.com/w320/bd.png" },
  { code: "pa-IN", name: "Punjabi", flag: "https://flagcdn.com/w320/in.png" },
  { code: "gu-IN", name: "Gujarati", flag: "https://flagcdn.com/w320/in.png" },
  { code: "ta-IN", name: "Tamil", flag: "https://flagcdn.com/w320/in.png" },
  { code: "hi-IN", name: "Hindi", flag: "https://flagcdn.com/w320/in.png" },
  { code: "ur-PK", name: "Urdu", flag: "https://flagcdn.com/w320/pk.png" },
  { code: "sw-KE", name: "Swahili", flag: "https://flagcdn.com/w320/ke.png" },
  {
    code: "lt-LT",
    name: "Lithuanian",
    flag: "https://flagcdn.com/w320/lt.png",
  },
  { code: "lv-LV", name: "Latvian", flag: "https://flagcdn.com/w320/lv.png" },
  { code: "et-EE", name: "Estonian", flag: "https://flagcdn.com/w320/ee.png" },
  { code: "sl-SI", name: "Slovenian", flag: "https://flagcdn.com/w320/si.png" },
  { code: "hr-HR", name: "Croatian", flag: "https://flagcdn.com/w320/hr.png" },
  { code: "sr-RS", name: "Serbian", flag: "https://flagcdn.com/w320/rs.png" },
  {
    code: "mk-MK",
    name: "Macedonian",
    flag: "https://flagcdn.com/w320/mk.png",
  },
  { code: "sq-AL", name: "Albanian", flag: "https://flagcdn.com/w320/al.png" },
  { code: "hy-AM", name: "Armenian", flag: "https://flagcdn.com/w320/am.png" },
  { code: "ka-GE", name: "Georgian", flag: "https://flagcdn.com/w320/ge.png" },
  {
    code: "az-AZ",
    name: "Azerbaijani",
    flag: "https://flagcdn.com/w320/az.png",
  },
  { code: "mr-IN", name: "Marathi", flag: "https://flagcdn.com/w320/in.png" },
  { code: "kn-IN", name: "Kannada", flag: "https://flagcdn.com/w320/in.png" },
  { code: "ml-IN", name: "Malayalam", flag: "https://flagcdn.com/w320/in.png" },
  { code: "si-LK", name: "Sinhala", flag: "https://flagcdn.com/w320/lk.png" },
  { code: "my-MM", name: "Burmese", flag: "https://flagcdn.com/w320/mm.png" },
  { code: "ne-NP", name: "Nepali", flag: "https://flagcdn.com/w320/np.png" },
  { code: "km-KH", name: "Khmer", flag: "https://flagcdn.com/w320/kh.png" },
  { code: "lo-LA", name: "Lao", flag: "https://flagcdn.com/w320/la.png" },
  {
    code: "cu-RU",
    name: "Church Slavonic",
    flag: "https://flagcdn.com/w320/ru.png",
  },
  { code: "gl-ES", name: "Galician", flag: "https://flagcdn.com/w320/es.png" },
  { code: "eu-ES", name: "Basque", flag: "https://flagcdn.com/w320/es.png" },
  { code: "ca-ES", name: "Catalan", flag: "https://flagcdn.com/w320/es.png" },
  { code: "mt-MT", name: "Maltese", flag: "https://flagcdn.com/w320/mt.png" },
  { code: "tt-RU", name: "Tatar", flag: "https://flagcdn.com/w320/ru.png" },
  { code: "sa-IN", name: "Sanskrit", flag: "https://flagcdn.com/w320/in.png" },
  { code: "xh-ZA", name: "Xhosa", flag: "https://flagcdn.com/w320/za.png" },
  { code: "zu-ZA", name: "Zulu", flag: "https://flagcdn.com/w320/za.png" },
  { code: "st-ZA", name: "Sesotho", flag: "https://flagcdn.com/w320/za.png" },
  { code: "ts-ZA", name: "Tswana", flag: "https://flagcdn.com/w320/za.png" },
  { code: "tn-ZA", name: "Tswana", flag: "https://flagcdn.com/w320/za.png" },
  {
    code: "sw-TZ",
    name: "Swahili (Tanzania)",
    flag: "https://flagcdn.com/w320/tz.png",
  },
  { code: "br-FR", name: "Breton", flag: "https://flagcdn.com/w320/fr.png" },
  { code: "sc-IT", name: "Sardinian", flag: "https://flagcdn.com/w320/it.png" },
  { code: "cy-GB", name: "Welsh", flag: "https://flagcdn.com/w320/gb.png" },
  {
    code: "gd-GB",
    name: "Scottish Gaelic",
    flag: "https://flagcdn.com/w320/gb.png",
  },
  {
    code: "ku-TR",
    name: "Kurdish (Kurmanji)",
    flag: "https://flagcdn.com/w320/tr.png",
  },
  { code: "ky-KG", name: "Kyrgyz", flag: "https://flagcdn.com/w320/kg.png" },
  { code: "ba-RU", name: "Bashkir", flag: "https://flagcdn.com/w320/ru.png" },
  { code: "jv-ID", name: "Javanese", flag: "https://flagcdn.com/w320/id.png" },
  { code: "su-ID", name: "Sundanese", flag: "https://flagcdn.com/w320/id.png" },
  {
    code: "rw-RW",
    name: "Kinyarwanda",
    flag: "https://flagcdn.com/w320/rw.png",
  },
];

export default languages;
